services:
- name: flask-api
  type: web
  runtime: python
  region: oregon
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: ./start.sh
  envVars:
    - key: PORT
      value: 10000